### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by Maijjay** [junyuan-fang/WebChatting#1]
Testasin nettisivua ja käytettävissä olevat toiminnot näyttivät toimivan hyvin! Sivusto näytti myös hyvältä, mutta en ole varma onko id - numerointia tarpeellista esittää nettisivulla käyttäjälle. En löytänyt mahdollisuutta kirjautua ulos, eli sen vielä lisäisin!

**Comment by junyuan-fang** [comment]
Kiitos palautteesta, oikeasta yläkulmasta löytyy "Logout". Sen avulla pystyy kirjautumaan ulos.
